// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw-ycWgCLIEjGpVmALOGXi308VvnNMihA',
    appId: '1:776083554780:web:df533b47c535329ba5cf19',
    messagingSenderId: '776083554780',
    projectId: 'article-eman-2026',
    authDomain: 'article-eman-2026.firebaseapp.com',
    storageBucket: 'article-eman-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYX0vg4dMVYZuNNhCMLN-SlHTXcZ9mBpY',
    appId: '1:776083554780:android:80538baa47c66b6fa5cf19',
    messagingSenderId: '776083554780',
    projectId: 'article-eman-2026',
    storageBucket: 'article-eman-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuWjtr2cfHXxQ1G5MXmKVQjPPrrT4UBsM',
    appId: '1:776083554780:ios:0baa76a4d06c06fda5cf19',
    messagingSenderId: '776083554780',
    projectId: 'article-eman-2026',
    storageBucket: 'article-eman-2026.firebasestorage.app',
    androidClientId: '776083554780-i80hm7gq206nlqditr7djqpbg6aadj4j.apps.googleusercontent.com',
    iosClientId: '776083554780-rkh5oeu9shlb54ta7ojqg95jvj2f5sgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.articleFlow',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuWjtr2cfHXxQ1G5MXmKVQjPPrrT4UBsM',
    appId: '1:776083554780:ios:0baa76a4d06c06fda5cf19',
    messagingSenderId: '776083554780',
    projectId: 'article-eman-2026',
    storageBucket: 'article-eman-2026.firebasestorage.app',
    androidClientId: '776083554780-i80hm7gq206nlqditr7djqpbg6aadj4j.apps.googleusercontent.com',
    iosClientId: '776083554780-rkh5oeu9shlb54ta7ojqg95jvj2f5sgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.articleFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw-ycWgCLIEjGpVmALOGXi308VvnNMihA',
    appId: '1:776083554780:web:93a5fc556c909b08a5cf19',
    messagingSenderId: '776083554780',
    projectId: 'article-eman-2026',
    authDomain: 'article-eman-2026.firebaseapp.com',
    storageBucket: 'article-eman-2026.firebasestorage.app',
  );
}
